config/routes.rb
Solutions::Application.routes.draw do
  devise_for :users

  resources :teams, except: [:destroy, :edit, :index] do
    get :new_team, on: :collection
    get :download_regulations, on: :collection
  end

  resources :students

  root to: 'home#index'

  get '*a', to: 'application#render_error' if Rails.env.production?
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-block alert-<%= key %>">
    <button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button>
    <p><%= raw(value) %></p>
  </div>
<% end %>

app/views/layouts/_menu_left.html.erb
<div id="sidebar" class="sidebar <%= cookies[:menu_state] %>">

  <div id="sidebar-shortcuts" class='sidebar-shortcuts'>
    <div id="sidebar-shortcuts-large" class='sidebar-shortcuts-large'>
      <button class="btn btn-small btn-success"><i class="icon-signal"></i></button>
      <button class="btn btn-small btn-info"><i class="icon-pencil"></i></button>
      <button class="btn btn-small btn-warning"><i class="icon-group"></i></button>
      <button class="btn btn-small btn-danger"><i class="icon-cogs"></i></button>
    </div>
    <div id="sidebar-shortcuts-mini" class='sidebar-shortcuts-mini'>
      <span class="btn btn-success"></span>
      <span class="btn btn-info"></span>
      <span class="btn btn-warning"></span>
      <span class="btn btn-danger"></span>
    </div>
  </div>

  <ul class="nav nav-list">
    <li id='menu_sing_up'>
      <a href="<%= new_team_teams_path %>">
        <i class="menu-icon icon-pencil"></i>
        <span class='menu-text'>Cadastre sua equipe !!!</span>
      </a>
      <ul class="submenu">
      </ul>
    </li>
  </ul>

  <ul class="nav nav-list">
    <li id='menu_talk_with_us'>
      <a href="#">
        <i class="menu-icon icon-comments"></i>
        <span class='menu-text'>Fale conosco</span>
      </a>
      <ul class="submenu">
      </ul>
    </li>
  </ul>

  <div class="sidebar-collapse" id="sidebar-collapse">
    <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
  </div>
</div>

app/views/layouts/_menu_user_settings.html.erb
<ul class="nav ace-nav">
  <li class="light-blue">
    <ul id="user_menu" class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
      <li><%= link_to raw("<i class='icon-user'></i> #{t 'profile'}"), edit_user_registration_path %></li>
      <li class="divider"></li>
      <li><%= link_to raw("<i class='icon-off'></i> #{t 'logout'}"), destroy_user_session_path, { method: :delete } %></li>
    </ul>
  </li>
</ul>

app/views/layouts/_modal.html.erb
<div class="bootbox modal in" id="modal-window" tabindex='-1'>
  <div class='modal-dialog'>
    <div class='modal-content' id="modal-content">
      <div class="modal-body">Hello world!</div>
      <div class="modal-footer">
        <a class="btn null">Cancel</a>
        <a class="btn btn-primary">OK</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<li class="grey">
  <a data-toggle="dropdown" class="dropdown-toggle" href="#" id="notifications">
    <i class="icon-bell-alt"></i>
    <% if @not_seen_notifications > 0 %>
      <span class="badge badge-important"><%= @not_seen_notifications %></span>
    <% end %>
  </a>

  <ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
    <li class="dropdown-header">
      <i class="icon-warning-sign"></i>
      Notificações
    </li>

    <% @notifications.each do |notification| %>
      <li>
        <a href="<%= notification_url(notification) %>">
        <span class="msg-body">
          <span class="msg-title">
            <%= raw("<i class='icon-remove-sign red'> Erro:</i>") if notification.error %>
            <%= notification.abbreviated_message %>
          </span>
        </span>
        </a>
      </li>
    <% end %>

    <li>
      <a href="#">
        <%= link_to raw("Ver todas <i class='icon-arrow-right'></i>"),
          general_notifications_path %>
      </a>
    </li>
  </ul>
</li>

app/views/layouts/_status_bar_top.html.erb
<div id="breadcrumbs" class="breadcrumbs">
  <div class="breadcrumb">
  </div>
</div>

app/views/layouts/_submenu.html.erb
<li id='sub_<%= controller %>'>
  <%= link_to raw("<i class='icon-double-angle-right'></i> <span>#{@name}</span>"),
              send(@path) if can?(:index, controller.to_sym) %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Business Academy</title>
  <script>
    var environment = '<%= Rails.env %>',
        current_menu = '<%= menu_id(:menu) %>',
        current_submenu = '<%= menu_id(:sub) %>';
  </script>

  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag 'base/jquery-1.9.1' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_path('logo.png') %>

</head>
<body class='skin-1'>
  <div class="navbar navbar-default" id='navbar'>
    <div class="navbar-container" id='navbar-container'>
      <div class="navbar-header pull-left">
        <%= link_to 'Business Academy', root_path, class: 'navbar-brand' %>
      </div>
      <div class="navbar-header pull-right" role='navigation'>
        <%= render 'layouts/menu_user_settings' %>
      </div>
    </div>
  </div>

  <div class="main-container" id="main-container">
    <div class='main-container-inner'>
      <a class="menu-toggler" id="menu-toggler" href="#"><span class="menu-text"></span></a>
      <%= render 'layouts/menu_left' %>

      <div class="main-content">
        <%= render 'layouts/status_bar_top' %>
        <div class="page-content">
          <%= render 'layouts/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
    <i class="icon-double-angle-up icon-only bigger-110"></i>
  </a>

  <%= render 'layouts/modal' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag controller_name if controller_asset? %>
</body>
</html>

app/views/layouts/default_mail.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Business Academy</title>
  <style>
    a {
      color: #394c65 !important;
    }
    a:hover {
      color: #737373 !important;;
    }
    a:visited {
      color: #405165 !important;;
    }
    .color-email {
      color: #405165 !important;;
    }
  </style>
</head>
<body style="width: 100%;
  background-image: url('http://mkt.redetempo.com.br/telegestor/feeds/bg-tempo.png');
  background-repeat: no-repeat; background-size:cover; ">
<div style="margin: 0 auto; width: 900px">
  <table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0"
         style="padding:30px;">
    <tr>
      <td align="left">
        <img src="<%= attachments['logo.png'].url %>" width="250"
             height="126" border="0" style=" display:block;" />
        <br/>
        <br/>
      </td>
    </tr>
    <tr>
      <td>
        <div style="font-family: Segoe UI, Arial, Helvetica, sans-serif;
          font-size: 14px; display: block; clear: both; text-align: justify; color: #737373;">
          <%= yield %>
        </div>
      </td>
    </tr>
    <br/>
    <br/>
    <br/>
  </table>
</div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Probitate - Login</title>
    <%= stylesheet_link_tag :application %>
    <%= csrf_meta_tags %>
  </head>

  <body class="login-layout back_login">
    <div class="container-fluid" id="main-container">
      <div id="main-content">
        <div class="row-fluid">
          <div class="login-container">
            <div class="row-fluid">
              <div class="center">
                <h1>
                  <div class='inline-block titles'>
                    <span class='title-1'>Solutions</span><br>
                  </div>
                </h1>
              </div>
            </div>

            <div class="space-6"></div>

            <div class="row-fluid">
              <div class="position-relative">
                <div id="login-box" class="visible widget-box no-border">
                  <div class="widget-body">
                    <div class="widget-main"><%= yield %></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/mark_notification_as_seen.js.erb
<% if @not_seen_notifications > 0 %>
  $('#notifications').find('span').html('<%= @not_seen_notifications %>');
<% else %>
  $('#notifications').find('span').remove();
<% end %>